mass: 1.2
arm_length: 0.3

inertia: [0.01, 0.01, 0.02]
drag_coeff: [0.4, 0.316, 0.23]
# drag_coeff: [0.36, 0.284, 0.207] #0.9D
# drag_coeff: [0.44, 0.348, 0.253] #1.1D
torque_coeff: 0.0133

omega_xy_max: 6
omega_z_max: 2

thrust_min: 0.0
thrust_max: 6.9   # max accel z: 23m/s^2
